services:
  # ==========================================
  # SERVIÇO 1: O Backend (Java Spring Boot)
  # ==========================================
  backend:
    build: ./backend             # Diz ao Docker onde está o Dockerfile do Java
    container_name: marketlens-backend
    ports:
      - "8080:8080"              # Mapeia a porta 8080 do container para o seu PC
    env_file:             # Diz ao Docker para carregar as variáveis de ambiente do arquivo .env
      - .env                
    volumes:                      # Monta um volume para persistir os dados do H2 mesmo se o container for parado
      - dados_h2:/dados_db        
  # ==========================================
  # SERVIÇO 2: O Frontend (React + Nginx)
  # ==========================================
  frontend:
    build: ./frontend            # Diz ao Docker onde está o Dockerfile do React
    container_name: marketlens-frontend
    ports:
      - "80:80"                  # Mapeia a porta 80 do Nginx para a porta 80 do seu PC
    depends_on:
      - backend                  # Só inicia o frontend depois que o backend começar
# ==========================================
# VOLUME PARA O H2 (PERSISTÊNCIA DE DADOS)
# ==========================================
volumes:
  dados_h2: